name: Coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    name: Test coverage py-${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: make dev

      - name: Run all tests for coverage report
        run: make run-all-tests-w-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
