name: Release

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.task.name }} py-${{ matrix.python-version }}(${{ matrix.os }})
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        task:
          - name: Lint code
            run: make lint
          - name: Run tests
            run: make test

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM & Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install-dev

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PDM & Python 3.10
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"

      - name: Build distribution
        run: pdm build

      # - name: Publish package to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   if: github.repository == 'spraakbanken/karp-lex' && !startsWith(github.ref, 'refs/tags/')
      #   continue-on-error: true
      #   with:
      #     user: __token__
      #     password: ${{ secrets.TEST_PYPI_PASSWORD }}
      #     repository_url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.repository == 'spraakbanken/karp-lex-core' && startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
